"""create db

Revision ID: 963ffa3c9692
Revises: 458a23cb9aca
Create Date: 2025-06-03 20:23:16.754895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '963ffa3c9692'
down_revision: Union[str, None] = '458a23cb9aca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipments_contact_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('sender_name', sa.String(), nullable=False),
    sa.Column('sender_phone', sa.String(), nullable=False),
    sa.Column('sender_address', sa.String(), nullable=False),
    sa.Column('receiver_name', sa.String(), nullable=False),
    sa.Column('receiver_phone', sa.String(), nullable=False),
    sa.Column('receiver_address', sa.String(), nullable=False),
    sa.Column('info_provider_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['info_provider_id'], ['users.id'], name=op.f('fk_shipments_contact_info_info_provider_id_users')),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], name=op.f('fk_shipments_contact_info_shipment_id_shipments')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipments_contact_info')
    # ### end Alembic commands ###
